"""tentativa_config_server_default_address_id

Revision ID: 7ec6f17b775c
Revises: bb497b8c6cf6
Create Date: 2025-06-05 12:03:44.541113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7ec6f17b775c'
down_revision: Union[str, None] = 'bb497b8c6cf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Tabela addresses
    op.execute("ALTER TABLE addresses MODIFY COLUMN address_id VARCHAR(36) NOT NULL DEFAULT (UUID())")

    # Tabela categories
    op.execute("ALTER TABLE categories MODIFY COLUMN category_id VARCHAR(36) NOT NULL DEFAULT (UUID())")

    # Tabela messages
    op.execute("ALTER TABLE messages MODIFY COLUMN message_id VARCHAR(36) NOT NULL DEFAULT (UUID())")

    # Tabela order_items
    op.execute("ALTER TABLE order_items MODIFY COLUMN order_item_id VARCHAR(36) NOT NULL DEFAULT (UUID())")

    # Tabela orders
    op.execute("ALTER TABLE orders MODIFY COLUMN order_id VARCHAR(36) NOT NULL DEFAULT (UUID())")

    # Tabela products
    op.execute("ALTER TABLE products MODIFY COLUMN product_id VARCHAR(36) NOT NULL DEFAULT (UUID())")

    # Tabela reviews
    op.execute("ALTER TABLE reviews MODIFY COLUMN review_id VARCHAR(36) NOT NULL DEFAULT (UUID())")

    # Tabela users
    op.execute("ALTER TABLE users MODIFY COLUMN user_id VARCHAR(36) NOT NULL DEFAULT (UUID())")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Tabela users
    op.execute("ALTER TABLE users MODIFY COLUMN user_id VARCHAR(36) NOT NULL") # Remove o default

    # Tabela reviews
    op.execute("ALTER TABLE reviews MODIFY COLUMN review_id VARCHAR(36) NOT NULL")

    # Tabela products
    op.execute("ALTER TABLE products MODIFY COLUMN product_id VARCHAR(36) NOT NULL")

    # Tabela orders
    op.execute("ALTER TABLE orders MODIFY COLUMN order_id VARCHAR(36) NOT NULL")

    # Tabela order_items
    op.execute("ALTER TABLE order_items MODIFY COLUMN order_item_id VARCHAR(36) NOT NULL")

    # Tabela messages
    op.execute("ALTER TABLE messages MODIFY COLUMN message_id VARCHAR(36) NOT NULL")

    # Tabela categories
    op.execute("ALTER TABLE categories MODIFY COLUMN category_id VARCHAR(36) NOT NULL")

    # Tabela addresses
    op.execute("ALTER TABLE addresses MODIFY COLUMN address_id VARCHAR(36) NOT NULL")
    # Se as colunas eram originalmente NULLABLE=True antes desta migração,
    # você precisaria reverter para NULLABLE=True no downgrade, ex:
    # op.execute("ALTER TABLE addresses MODIFY COLUMN address_id VARCHAR(36) NULL")
