"""fix cart problems

Revision ID: ae59d265da3e
Revises: 112b271c565d
Create Date: 2025-06-09 21:34:24.182298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ae59d265da3e'
down_revision: Union[str, None] = '112b271c565d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('cart_id', sa.String(length=36), nullable=False),
    sa.Column('buyer_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.buyer_id'], ),
    sa.PrimaryKeyConstraint('cart_id')
    )
    op.create_table('cart_items',
    sa.Column('cart_item_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.cart_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('cart_item_id')
    )
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.alter_column('address_id',
               existing_type=mysql.VARCHAR(length=36),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_id', sa.String(length=36), nullable=True))
        batch_op.create_unique_constraint(None, ['address_id'])
        batch_op.create_foreign_key(None, 'addresses', ['address_id'], ['address_id'])
        batch_op.drop_column('delivery_address')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_address', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('address_id')

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.alter_column('address_id',
               existing_type=mysql.VARCHAR(length=36),
               server_default=sa.text('(uuid())'),
               existing_nullable=False)

    op.drop_table('cart_items')
    op.drop_table('carts')
    # ### end Alembic commands ###
