"""fix pk generation

Revision ID: 112b271c565d
Revises: 7337baba6b02
Create Date: 2025-06-05 13:01:26.687780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '112b271c565d'
down_revision: Union[str, None] = '7337baba6b02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=mysql.VARCHAR(length=36),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('message_id',
               existing_type=mysql.VARCHAR(length=36),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('order_item_id',
               existing_type=mysql.VARCHAR(length=36),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('order_id',
               existing_type=mysql.VARCHAR(length=36),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=mysql.VARCHAR(length=36),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('review_id',
               existing_type=mysql.VARCHAR(length=36),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.VARCHAR(length=36),
               server_default=None,
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.VARCHAR(length=36),
               server_default=sa.text('(uuid())'),
               existing_nullable=False)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('review_id',
               existing_type=mysql.VARCHAR(length=36),
               server_default=sa.text('(uuid())'),
               existing_nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=mysql.VARCHAR(length=36),
               server_default=sa.text('(uuid())'),
               existing_nullable=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('order_id',
               existing_type=mysql.VARCHAR(length=36),
               server_default=sa.text('(uuid())'),
               existing_nullable=False)

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('order_item_id',
               existing_type=mysql.VARCHAR(length=36),
               server_default=sa.text('(uuid())'),
               existing_nullable=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('message_id',
               existing_type=mysql.VARCHAR(length=36),
               server_default=sa.text('(uuid())'),
               existing_nullable=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=mysql.VARCHAR(length=36),
               server_default=sa.text('(uuid())'),
               existing_nullable=False)

    # ### end Alembic commands ###
