"""create users and addresses tables

Revision ID: 00c989113506
Revises: 
Create Date: 2025-06-03 17:23:42.650673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '00c989113506'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('addresses')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('street', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('number', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('complement', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('neighborhood', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('city', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('state', mysql.VARCHAR(length=2), nullable=False),
    sa.Column('zip_code', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
